

import { Header } from '@/components/features/assemblies/layout/Header'
import HeaderMobile from '@/components/features/assemblies/layout/header-mobile'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <div className="flex flex-col h-full">
      <div className='z-40'>
        <Header />
        <HeaderMobile />
      </div>
      <div className="flex-1 w-full m-auto  w-full z-0">{children}</div>
    </div>
  )
}
