

import { Header } from '@/components/features/assemblies/homeAssemblies/Header'
import HeaderMobile from '@/components/features/assemblies/homeAssemblies/header-mobile'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <div className="flex flex-col h-full">
    <Header />
    <HeaderMobile />
    <div className="flex-1 w-full m-auto py-[80px] px-5 w-full">{children}</div>
  </div>
  )
}
